apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orin.fullname" . }}
  labels: {{- include "orin.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.adminToken | quote }}
  ENCRYPTION_KEY: {{ .Values.encryptionKey | quote }}
  {{- $dbURL := .Values.databaseUrl -}}
  {{- if not $dbURL }}
  {{- if .Values.postgres.enabled }}
  {{- $dbURL = printf "postgres://%s:%s@%s:5432/%s?sslmode=disable" .Values.postgres.username .Values.postgres.password (include "orin.postgres.fullname" .) .Values.postgres.database -}}
  {{- else }}
  {{- $dbURL = required "databaseUrl is required when postgres.enabled=false" .Values.databaseUrl -}}
  {{- end }}
  {{- end }}
  DATABASE_URL: {{ $dbURL | quote }}
