apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-ui.fullname" . }}
  labels: {{- include "k8s-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.adminToken | quote }}
  ENCRYPTION_KEY: {{ .Values.encryptionKey | quote }}
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
