// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/reposerver/reposerver.proto

package reposerverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepoServer_Render_FullMethodName          = "/reposerver.RepoServer/Render"
	RepoServer_RenderSHA_FullMethodName       = "/reposerver.RepoServer/RenderSHA"
	RepoServer_ResolveRevision_FullMethodName = "/reposerver.RepoServer/ResolveRevision"
	RepoServer_ListCommits_FullMethodName     = "/reposerver.RepoServer/ListCommits"
	RepoServer_GetCommit_FullMethodName       = "/reposerver.RepoServer/GetCommit"
	RepoServer_DiffPaths_FullMethodName       = "/reposerver.RepoServer/DiffPaths"
	RepoServer_ReadRawFile_FullMethodName     = "/reposerver.RepoServer/ReadRawFile"
)

// RepoServerClient is the client API for RepoServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RepoServer renders Git repository contents into Kubernetes manifests
// and provides git introspection (commits, diffs, raw files).
type RepoServerClient interface {
	// Render manifests for an application at its target revision.
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
	// Render manifests at an explicit commit SHA.
	RenderSHA(ctx context.Context, in *RenderSHARequest, opts ...grpc.CallOption) (*RenderResponse, error)
	// Resolve a symbolic ref (branch/tag) to a commit SHA.
	ResolveRevision(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	// List recent commits for the application's path.
	ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
	// Return commit metadata for a specific SHA.
	GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*GetCommitResponse, error)
	// Unified diff of a path between two commits.
	DiffPaths(ctx context.Context, in *DiffPathsRequest, opts ...grpc.CallOption) (*DiffPathsResponse, error)
	// Read a raw file at a given revision.
	ReadRawFile(ctx context.Context, in *ReadRawFileRequest, opts ...grpc.CallOption) (*ReadRawFileResponse, error)
}

type repoServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRepoServerClient(cc grpc.ClientConnInterface) RepoServerClient {
	return &repoServerClient{cc}
}

func (c *repoServerClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, RepoServer_Render_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServerClient) RenderSHA(ctx context.Context, in *RenderSHARequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, RepoServer_RenderSHA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServerClient) ResolveRevision(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, RepoServer_ResolveRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServerClient) ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, RepoServer_ListCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServerClient) GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*GetCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommitResponse)
	err := c.cc.Invoke(ctx, RepoServer_GetCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServerClient) DiffPaths(ctx context.Context, in *DiffPathsRequest, opts ...grpc.CallOption) (*DiffPathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffPathsResponse)
	err := c.cc.Invoke(ctx, RepoServer_DiffPaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServerClient) ReadRawFile(ctx context.Context, in *ReadRawFileRequest, opts ...grpc.CallOption) (*ReadRawFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadRawFileResponse)
	err := c.cc.Invoke(ctx, RepoServer_ReadRawFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepoServerServer is the server API for RepoServer service.
// All implementations must embed UnimplementedRepoServerServer
// for forward compatibility.
//
// RepoServer renders Git repository contents into Kubernetes manifests
// and provides git introspection (commits, diffs, raw files).
type RepoServerServer interface {
	// Render manifests for an application at its target revision.
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
	// Render manifests at an explicit commit SHA.
	RenderSHA(context.Context, *RenderSHARequest) (*RenderResponse, error)
	// Resolve a symbolic ref (branch/tag) to a commit SHA.
	ResolveRevision(context.Context, *ResolveRequest) (*ResolveResponse, error)
	// List recent commits for the application's path.
	ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error)
	// Return commit metadata for a specific SHA.
	GetCommit(context.Context, *GetCommitRequest) (*GetCommitResponse, error)
	// Unified diff of a path between two commits.
	DiffPaths(context.Context, *DiffPathsRequest) (*DiffPathsResponse, error)
	// Read a raw file at a given revision.
	ReadRawFile(context.Context, *ReadRawFileRequest) (*ReadRawFileResponse, error)
	mustEmbedUnimplementedRepoServerServer()
}

// UnimplementedRepoServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepoServerServer struct{}

func (UnimplementedRepoServerServer) Render(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedRepoServerServer) RenderSHA(context.Context, *RenderSHARequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderSHA not implemented")
}
func (UnimplementedRepoServerServer) ResolveRevision(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveRevision not implemented")
}
func (UnimplementedRepoServerServer) ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommits not implemented")
}
func (UnimplementedRepoServerServer) GetCommit(context.Context, *GetCommitRequest) (*GetCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommit not implemented")
}
func (UnimplementedRepoServerServer) DiffPaths(context.Context, *DiffPathsRequest) (*DiffPathsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffPaths not implemented")
}
func (UnimplementedRepoServerServer) ReadRawFile(context.Context, *ReadRawFileRequest) (*ReadRawFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadRawFile not implemented")
}
func (UnimplementedRepoServerServer) mustEmbedUnimplementedRepoServerServer() {}
func (UnimplementedRepoServerServer) testEmbeddedByValue()                    {}

// UnsafeRepoServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepoServerServer will
// result in compilation errors.
type UnsafeRepoServerServer interface {
	mustEmbedUnimplementedRepoServerServer()
}

func RegisterRepoServerServer(s grpc.ServiceRegistrar, srv RepoServerServer) {
	// If the following call panics, it indicates UnimplementedRepoServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepoServer_ServiceDesc, srv)
}

func _RepoServer_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServerServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoServer_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServerServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoServer_RenderSHA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderSHARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServerServer).RenderSHA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoServer_RenderSHA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServerServer).RenderSHA(ctx, req.(*RenderSHARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoServer_ResolveRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServerServer).ResolveRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoServer_ResolveRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServerServer).ResolveRevision(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoServer_ListCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServerServer).ListCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoServer_ListCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServerServer).ListCommits(ctx, req.(*ListCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoServer_GetCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServerServer).GetCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoServer_GetCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServerServer).GetCommit(ctx, req.(*GetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoServer_DiffPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffPathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServerServer).DiffPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoServer_DiffPaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServerServer).DiffPaths(ctx, req.(*DiffPathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoServer_ReadRawFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRawFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServerServer).ReadRawFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoServer_ReadRawFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServerServer).ReadRawFile(ctx, req.(*ReadRawFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepoServer_ServiceDesc is the grpc.ServiceDesc for RepoServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepoServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reposerver.RepoServer",
	HandlerType: (*RepoServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Render",
			Handler:    _RepoServer_Render_Handler,
		},
		{
			MethodName: "RenderSHA",
			Handler:    _RepoServer_RenderSHA_Handler,
		},
		{
			MethodName: "ResolveRevision",
			Handler:    _RepoServer_ResolveRevision_Handler,
		},
		{
			MethodName: "ListCommits",
			Handler:    _RepoServer_ListCommits_Handler,
		},
		{
			MethodName: "GetCommit",
			Handler:    _RepoServer_GetCommit_Handler,
		},
		{
			MethodName: "DiffPaths",
			Handler:    _RepoServer_DiffPaths_Handler,
		},
		{
			MethodName: "ReadRawFile",
			Handler:    _RepoServer_ReadRawFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reposerver/reposerver.proto",
}
