// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/reposerver/reposerver.proto

package reposerverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RepoUrl        string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	TargetRevision string                 `protobuf:"bytes,3,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	Path           string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	SourceType     string                 `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`         // "kustomize", "helm", "directory"
	AppNameLabel   string                 `protobuf:"bytes,6,opt,name=app_name_label,json=appNameLabel,proto3" json:"app_name_label,omitempty"` // used for tracking labels
	DestNamespace  string                 `protobuf:"bytes,7,opt,name=dest_namespace,json=destNamespace,proto3" json:"dest_namespace,omitempty"`
	HelmValueFiles []string               `protobuf:"bytes,8,rep,name=helm_value_files,json=helmValueFiles,proto3" json:"helm_value_files,omitempty"`
	HelmValuesJson string                 `protobuf:"bytes,9,opt,name=helm_values_json,json=helmValuesJson,proto3" json:"helm_values_json,omitempty"` // inline helm values (JSON)
	// Auth credentials (optional, sent per-call for gRPC repo server).
	Username      string `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	Password      string `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	SshPrivateKey string `protobuf:"bytes,12,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppRef) Reset() {
	*x = AppRef{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRef) ProtoMessage() {}

func (x *AppRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRef.ProtoReflect.Descriptor instead.
func (*AppRef) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{0}
}

func (x *AppRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppRef) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *AppRef) GetTargetRevision() string {
	if x != nil {
		return x.TargetRevision
	}
	return ""
}

func (x *AppRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AppRef) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AppRef) GetAppNameLabel() string {
	if x != nil {
		return x.AppNameLabel
	}
	return ""
}

func (x *AppRef) GetDestNamespace() string {
	if x != nil {
		return x.DestNamespace
	}
	return ""
}

func (x *AppRef) GetHelmValueFiles() []string {
	if x != nil {
		return x.HelmValueFiles
	}
	return nil
}

func (x *AppRef) GetHelmValuesJson() string {
	if x != nil {
		return x.HelmValuesJson
	}
	return ""
}

func (x *AppRef) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AppRef) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AppRef) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

type RenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *AppRef                `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{1}
}

func (x *RenderRequest) GetApp() *AppRef {
	if x != nil {
		return x.App
	}
	return nil
}

type RenderSHARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *AppRef                `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Sha           string                 `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderSHARequest) Reset() {
	*x = RenderSHARequest{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSHARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSHARequest) ProtoMessage() {}

func (x *RenderSHARequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSHARequest.ProtoReflect.Descriptor instead.
func (*RenderSHARequest) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{2}
}

func (x *RenderSHARequest) GetApp() *AppRef {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *RenderSHARequest) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type RenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      string                 `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Manifests     []string               `protobuf:"bytes,2,rep,name=manifests,proto3" json:"manifests,omitempty"` // YAML documents, concatenated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{3}
}

func (x *RenderResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *RenderResponse) GetManifests() []string {
	if x != nil {
		return x.Manifests
	}
	return nil
}

type ResolveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl        string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	TargetRevision string                 `protobuf:"bytes,2,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password       string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	SshPrivateKey  string                 `protobuf:"bytes,5,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *ResolveRequest) GetTargetRevision() string {
	if x != nil {
		return x.TargetRevision
	}
	return ""
}

func (x *ResolveRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResolveRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResolveRequest) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveResponse) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type ListCommitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	SshPrivateKey string                 `protobuf:"bytes,6,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsRequest) Reset() {
	*x = ListCommitsRequest{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsRequest) ProtoMessage() {}

func (x *ListCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsRequest.ProtoReflect.Descriptor instead.
func (*ListCommitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{6}
}

func (x *ListCommitsRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *ListCommitsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListCommitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommitsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListCommitsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ListCommitsRequest) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

type ListCommitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*CommitInfo          `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsResponse) Reset() {
	*x = ListCommitsResponse{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsResponse) ProtoMessage() {}

func (x *ListCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsResponse.ProtoReflect.Descriptor instead.
func (*ListCommitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{7}
}

func (x *ListCommitsResponse) GetCommits() []*CommitInfo {
	if x != nil {
		return x.Commits
	}
	return nil
}

type CommitInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sha            string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	ShortSha       string                 `protobuf:"bytes,2,opt,name=short_sha,json=shortSha,proto3" json:"short_sha,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Author         string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	AuthorDateUnix int64                  `protobuf:"varint,5,opt,name=author_date_unix,json=authorDateUnix,proto3" json:"author_date_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitInfo) Reset() {
	*x = CommitInfo{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitInfo) ProtoMessage() {}

func (x *CommitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitInfo.ProtoReflect.Descriptor instead.
func (*CommitInfo) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{8}
}

func (x *CommitInfo) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *CommitInfo) GetShortSha() string {
	if x != nil {
		return x.ShortSha
	}
	return ""
}

func (x *CommitInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CommitInfo) GetAuthorDateUnix() int64 {
	if x != nil {
		return x.AuthorDateUnix
	}
	return 0
}

type GetCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Sha           string                 `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	SshPrivateKey string                 `protobuf:"bytes,5,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitRequest) Reset() {
	*x = GetCommitRequest{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitRequest) ProtoMessage() {}

func (x *GetCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitRequest.ProtoReflect.Descriptor instead.
func (*GetCommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommitRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *GetCommitRequest) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *GetCommitRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetCommitRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetCommitRequest) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

type GetCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        *CommitInfo            `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitResponse) Reset() {
	*x = GetCommitResponse{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitResponse) ProtoMessage() {}

func (x *GetCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitResponse.ProtoReflect.Descriptor instead.
func (*GetCommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommitResponse) GetCommit() *CommitInfo {
	if x != nil {
		return x.Commit
	}
	return nil
}

type DiffPathsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FromSha       string                 `protobuf:"bytes,3,opt,name=from_sha,json=fromSha,proto3" json:"from_sha,omitempty"`
	ToSha         string                 `protobuf:"bytes,4,opt,name=to_sha,json=toSha,proto3" json:"to_sha,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	SshPrivateKey string                 `protobuf:"bytes,7,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffPathsRequest) Reset() {
	*x = DiffPathsRequest{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffPathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffPathsRequest) ProtoMessage() {}

func (x *DiffPathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffPathsRequest.ProtoReflect.Descriptor instead.
func (*DiffPathsRequest) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{11}
}

func (x *DiffPathsRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *DiffPathsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiffPathsRequest) GetFromSha() string {
	if x != nil {
		return x.FromSha
	}
	return ""
}

func (x *DiffPathsRequest) GetToSha() string {
	if x != nil {
		return x.ToSha
	}
	return ""
}

func (x *DiffPathsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DiffPathsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DiffPathsRequest) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

type DiffPathsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          string                 `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffPathsResponse) Reset() {
	*x = DiffPathsResponse{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffPathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffPathsResponse) ProtoMessage() {}

func (x *DiffPathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffPathsResponse.ProtoReflect.Descriptor instead.
func (*DiffPathsResponse) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{12}
}

func (x *DiffPathsResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

type ReadRawFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	RelPath       string                 `protobuf:"bytes,3,opt,name=rel_path,json=relPath,proto3" json:"rel_path,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	SshPrivateKey string                 `protobuf:"bytes,6,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRawFileRequest) Reset() {
	*x = ReadRawFileRequest{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRawFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRawFileRequest) ProtoMessage() {}

func (x *ReadRawFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRawFileRequest.ProtoReflect.Descriptor instead.
func (*ReadRawFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{13}
}

func (x *ReadRawFileRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *ReadRawFileRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ReadRawFileRequest) GetRelPath() string {
	if x != nil {
		return x.RelPath
	}
	return ""
}

func (x *ReadRawFileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReadRawFileRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReadRawFileRequest) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

type ReadRawFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRawFileResponse) Reset() {
	*x = ReadRawFileResponse{}
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRawFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRawFileResponse) ProtoMessage() {}

func (x *ReadRawFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reposerver_reposerver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRawFileResponse.ProtoReflect.Descriptor instead.
func (*ReadRawFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_reposerver_reposerver_proto_rawDescGZIP(), []int{14}
}

func (x *ReadRawFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_proto_reposerver_reposerver_proto protoreflect.FileDescriptor

const file_proto_reposerver_reposerver_proto_rawDesc = "" +
	"\n" +
	"!proto/reposerver/reposerver.proto\x12\n" +
	"reposerver\"\x96\x03\n" +
	"\x06AppRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12'\n" +
	"\x0ftarget_revision\x18\x03 \x01(\tR\x0etargetRevision\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1f\n" +
	"\vsource_type\x18\x05 \x01(\tR\n" +
	"sourceType\x12$\n" +
	"\x0eapp_name_label\x18\x06 \x01(\tR\fappNameLabel\x12%\n" +
	"\x0edest_namespace\x18\a \x01(\tR\rdestNamespace\x12(\n" +
	"\x10helm_value_files\x18\b \x03(\tR\x0ehelmValueFiles\x12(\n" +
	"\x10helm_values_json\x18\t \x01(\tR\x0ehelmValuesJson\x12\x1a\n" +
	"\busername\x18\n" +
	" \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\v \x01(\tR\bpassword\x12&\n" +
	"\x0fssh_private_key\x18\f \x01(\tR\rsshPrivateKey\"5\n" +
	"\rRenderRequest\x12$\n" +
	"\x03app\x18\x01 \x01(\v2\x12.reposerver.AppRefR\x03app\"J\n" +
	"\x10RenderSHARequest\x12$\n" +
	"\x03app\x18\x01 \x01(\v2\x12.reposerver.AppRefR\x03app\x12\x10\n" +
	"\x03sha\x18\x02 \x01(\tR\x03sha\"J\n" +
	"\x0eRenderResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\tR\brevision\x12\x1c\n" +
	"\tmanifests\x18\x02 \x03(\tR\tmanifests\"\xb4\x01\n" +
	"\x0eResolveRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12'\n" +
	"\x0ftarget_revision\x18\x02 \x01(\tR\x0etargetRevision\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12&\n" +
	"\x0fssh_private_key\x18\x05 \x01(\tR\rsshPrivateKey\"#\n" +
	"\x0fResolveResponse\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\"\xb9\x01\n" +
	"\x12ListCommitsRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12&\n" +
	"\x0fssh_private_key\x18\x06 \x01(\tR\rsshPrivateKey\"G\n" +
	"\x13ListCommitsResponse\x120\n" +
	"\acommits\x18\x01 \x03(\v2\x16.reposerver.CommitInfoR\acommits\"\x97\x01\n" +
	"\n" +
	"CommitInfo\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12\x1b\n" +
	"\tshort_sha\x18\x02 \x01(\tR\bshortSha\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12(\n" +
	"\x10author_date_unix\x18\x05 \x01(\x03R\x0eauthorDateUnix\"\x9f\x01\n" +
	"\x10GetCommitRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03sha\x18\x02 \x01(\tR\x03sha\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12&\n" +
	"\x0fssh_private_key\x18\x05 \x01(\tR\rsshPrivateKey\"C\n" +
	"\x11GetCommitResponse\x12.\n" +
	"\x06commit\x18\x01 \x01(\v2\x16.reposerver.CommitInfoR\x06commit\"\xd3\x01\n" +
	"\x10DiffPathsRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\bfrom_sha\x18\x03 \x01(\tR\afromSha\x12\x15\n" +
	"\x06to_sha\x18\x04 \x01(\tR\x05toSha\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12&\n" +
	"\x0fssh_private_key\x18\a \x01(\tR\rsshPrivateKey\"'\n" +
	"\x11DiffPathsResponse\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\tR\x04diff\"\xc6\x01\n" +
	"\x12ReadRawFileRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x19\n" +
	"\brel_path\x18\x03 \x01(\tR\arelPath\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12&\n" +
	"\x0fssh_private_key\x18\x06 \x01(\tR\rsshPrivateKey\"/\n" +
	"\x13ReadRawFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent2\x94\x04\n" +
	"\n" +
	"RepoServer\x12?\n" +
	"\x06Render\x12\x19.reposerver.RenderRequest\x1a\x1a.reposerver.RenderResponse\x12E\n" +
	"\tRenderSHA\x12\x1c.reposerver.RenderSHARequest\x1a\x1a.reposerver.RenderResponse\x12J\n" +
	"\x0fResolveRevision\x12\x1a.reposerver.ResolveRequest\x1a\x1b.reposerver.ResolveResponse\x12N\n" +
	"\vListCommits\x12\x1e.reposerver.ListCommitsRequest\x1a\x1f.reposerver.ListCommitsResponse\x12H\n" +
	"\tGetCommit\x12\x1c.reposerver.GetCommitRequest\x1a\x1d.reposerver.GetCommitResponse\x12H\n" +
	"\tDiffPaths\x12\x1c.reposerver.DiffPathsRequest\x1a\x1d.reposerver.DiffPathsResponse\x12N\n" +
	"\vReadRawFile\x12\x1e.reposerver.ReadRawFileRequest\x1a\x1f.reposerver.ReadRawFileResponseB4Z2github.com/orin/orin/proto/reposerver;reposerverpbb\x06proto3"

var (
	file_proto_reposerver_reposerver_proto_rawDescOnce sync.Once
	file_proto_reposerver_reposerver_proto_rawDescData []byte
)

func file_proto_reposerver_reposerver_proto_rawDescGZIP() []byte {
	file_proto_reposerver_reposerver_proto_rawDescOnce.Do(func() {
		file_proto_reposerver_reposerver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reposerver_reposerver_proto_rawDesc), len(file_proto_reposerver_reposerver_proto_rawDesc)))
	})
	return file_proto_reposerver_reposerver_proto_rawDescData
}

var file_proto_reposerver_reposerver_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_reposerver_reposerver_proto_goTypes = []any{
	(*AppRef)(nil),              // 0: reposerver.AppRef
	(*RenderRequest)(nil),       // 1: reposerver.RenderRequest
	(*RenderSHARequest)(nil),    // 2: reposerver.RenderSHARequest
	(*RenderResponse)(nil),      // 3: reposerver.RenderResponse
	(*ResolveRequest)(nil),      // 4: reposerver.ResolveRequest
	(*ResolveResponse)(nil),     // 5: reposerver.ResolveResponse
	(*ListCommitsRequest)(nil),  // 6: reposerver.ListCommitsRequest
	(*ListCommitsResponse)(nil), // 7: reposerver.ListCommitsResponse
	(*CommitInfo)(nil),          // 8: reposerver.CommitInfo
	(*GetCommitRequest)(nil),    // 9: reposerver.GetCommitRequest
	(*GetCommitResponse)(nil),   // 10: reposerver.GetCommitResponse
	(*DiffPathsRequest)(nil),    // 11: reposerver.DiffPathsRequest
	(*DiffPathsResponse)(nil),   // 12: reposerver.DiffPathsResponse
	(*ReadRawFileRequest)(nil),  // 13: reposerver.ReadRawFileRequest
	(*ReadRawFileResponse)(nil), // 14: reposerver.ReadRawFileResponse
}
var file_proto_reposerver_reposerver_proto_depIdxs = []int32{
	0,  // 0: reposerver.RenderRequest.app:type_name -> reposerver.AppRef
	0,  // 1: reposerver.RenderSHARequest.app:type_name -> reposerver.AppRef
	8,  // 2: reposerver.ListCommitsResponse.commits:type_name -> reposerver.CommitInfo
	8,  // 3: reposerver.GetCommitResponse.commit:type_name -> reposerver.CommitInfo
	1,  // 4: reposerver.RepoServer.Render:input_type -> reposerver.RenderRequest
	2,  // 5: reposerver.RepoServer.RenderSHA:input_type -> reposerver.RenderSHARequest
	4,  // 6: reposerver.RepoServer.ResolveRevision:input_type -> reposerver.ResolveRequest
	6,  // 7: reposerver.RepoServer.ListCommits:input_type -> reposerver.ListCommitsRequest
	9,  // 8: reposerver.RepoServer.GetCommit:input_type -> reposerver.GetCommitRequest
	11, // 9: reposerver.RepoServer.DiffPaths:input_type -> reposerver.DiffPathsRequest
	13, // 10: reposerver.RepoServer.ReadRawFile:input_type -> reposerver.ReadRawFileRequest
	3,  // 11: reposerver.RepoServer.Render:output_type -> reposerver.RenderResponse
	3,  // 12: reposerver.RepoServer.RenderSHA:output_type -> reposerver.RenderResponse
	5,  // 13: reposerver.RepoServer.ResolveRevision:output_type -> reposerver.ResolveResponse
	7,  // 14: reposerver.RepoServer.ListCommits:output_type -> reposerver.ListCommitsResponse
	10, // 15: reposerver.RepoServer.GetCommit:output_type -> reposerver.GetCommitResponse
	12, // 16: reposerver.RepoServer.DiffPaths:output_type -> reposerver.DiffPathsResponse
	14, // 17: reposerver.RepoServer.ReadRawFile:output_type -> reposerver.ReadRawFileResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_reposerver_reposerver_proto_init() }
func file_proto_reposerver_reposerver_proto_init() {
	if File_proto_reposerver_reposerver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reposerver_reposerver_proto_rawDesc), len(file_proto_reposerver_reposerver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reposerver_reposerver_proto_goTypes,
		DependencyIndexes: file_proto_reposerver_reposerver_proto_depIdxs,
		MessageInfos:      file_proto_reposerver_reposerver_proto_msgTypes,
	}.Build()
	File_proto_reposerver_reposerver_proto = out.File
	file_proto_reposerver_reposerver_proto_goTypes = nil
	file_proto_reposerver_reposerver_proto_depIdxs = nil
}
